name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8

      - name: Create .env from GitHub Secrets/Vars
        run: |
          cat > .env << 'EOF'
          DEBUG=True
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DB_ENGINE=sqlite3
          ALLOWED_HOSTS=*
          EOF

      - name: System deps for Pillow
        run: |
          sudo apt-get update
           sudo apt-get install -y libjpeg-dev zlib1g-dev

      - name: Lint & Format
        run: |
            isort --profile black --check-only --diff .
            black --check .
            flake8 .

      - name: Run tests
        timeout-minutes: 5
        run: python manage.py test -v 2
